services:
  mysql:
    image: mysql:8.0
    container_name: devbook-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devbook
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
    ports:
      - "3306:3306"
    volumes:
      - ./sql/sql.sql:/docker-entrypoint-initdb.d/init.sql
      - devbook-mysql-data:/var/lib/mysql

volumes:
  devbook-mysql-data:
